---

- name: TUTOR | Ensure tutor group
  ansible.builtin.group:
    name: "{{ tutor_group }}"
    system: yes
    state: present
  tags:
    - tutor_install

- name: TUTOR | Ensure tutor user
  ansible.builtin.user:
    name: "{{ tutor_user }}"
    group: "{{ tutor_group }}"
    groups:
      - docker
    system: yes
    shell: "{{ tutor_user_shell }}"
    createhome: no
  tags:
    - tutor_install

- name: TUTOR | Check tutor version
  ansible.builtin.command: "{{ tutor_venv_path }}/{{ tutor_exec_name }} --version"
  register: tutor_check
  changed_when: false
  ignore_errors: true
  check_mode: no
  tags:
    - tutor_install

- name: TUTOR | Install python3 & native dependencies
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - build-essential
      - python3
      - python3-pip
      - python3-dev
      - libyaml-dev
      - git
  when: tutor_force_reinstall or tutor_check is failed or tutor_version not in tutor_check.stdout
  tags:
    - tutor_install

- name: TUTOR | Create virtualenv directory
  ansible.builtin.file:
    path: /opt/tutor
    state: directory
    mode: 'u+rwx'
    owner: "{{ tutor_user }}"
    group: "{{ tutor_group }}"
  when: tutor_force_reinstall or tutor_check is failed or tutor_version not in tutor_check.stdout
  tags:
    - tutor_install

- name: TUTOR | Install tutor from PyPI
  ansible.builtin.pip:
    name: "tutor[full]=={{ tutor_version }}"
    virtualenv: "{{ tutor_venv_path }}"
    virtualenv_python: /usr/bin/python3
  become: true
  become_user: "{{ tutor_user }}"
  when: tutor_force_reinstall or tutor_check is failed or tutor_version not in tutor_check.stdout
  tags:
    - tutor_install

- name: TUTOR | Checkout config repo
  ansible.builtin.git:
    repo: "{{ tutor_config_repo }}"
    dest: "{{ tutor_config_path }}"
    clone: yes
    update: yes
    version: "{{ tutor_config_version }}"
  register: tutor_repo
  become: true
  become_user: "{{ tutor_user }}"
  tags:
    - tutor_install

- name: TUTOR | Pull all required images
  ansible.builtin.git:
    repo: "{{ tutor_config_repo }}"
    dest: "{{ tutor_config_path }}"
    clone: yes
    update: yes
    version: "{{ tutor_config_version }}"
  register: tutor_repo
  become: true
  become_user: "{{ tutor_user }}"
  tags:
    - tutor_install
