---

- name: TUTOR | Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - tutor_install

- name: TUTOR | Configure
  ansible.builtin.import_tasks: config.yml
  environment:
    TUTOR_ROOT: "{{ tutor_config_path }}"
    TUTOR_PLUGINS_ROOT: "{{ tutor_config_path }}/plugins"
  tags:
    - tutor_configure

- name: TUTOR | Service
  ansible.builtin.import_tasks: service.yml
  tags:
    - tutor_service
