---

- name: TUTOR | Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - tutor_install

- name: TUTOR | SSH
  ansible.builtin.import_tasks: ssh.yml
  tags:
    - tutor_ssh

- name: TUTOR | Update
  ansible.builtin.import_tasks: update.yml
  tags:
    - tutor_update

- name: TUTOR | Configure
  ansible.builtin.import_tasks: config.yml
  environment:
    TUTOR_ROOT: "{{ tutor_config_path }}"
    TUTOR_PLUGINS_ROOT: "{{ tutor_config_path }}/plugins"
  tags:
    - tutor_configure

- name: TUTOR | Init
  ansible.builtin.import_tasks: init.yml
  tags:
    - tutor_init

- name: TUTOR | Service
  ansible.builtin.import_tasks: service.yml
  tags:
    - tutor_service

- name: TUTOR | Weekly goal emails
  ansible.builtin.import_tasks: wge.yml
  tags:
    - tutor_wge
  when: tutor_enable_weekly_goal_emails

- name: TUTOR | Include post-deploy tasks
  ansible.builtin.import_tasks: post_deploy.yml
  tags:
    - tutor_post_deploy

- name: ASPECTS | Include Aspects update tasks
  ansible.builtin.include_tasks: aspects_update.yml
  when: tutor_aspects_update | default(false) | bool
  tags:
    - tutor_aspects