##Here is describe post deploy action, like cleanup, liveness, readiness probes, etc.

- name: SYSTEM | Docker cleanup after deploy
  community.docker.docker_prune:
    system: yes
    all: yes
    force: yes
  become: true
  become_user: "{{ tutor_user }}"
  tags:
    - tutor_post_deploy