---
- name: Add forge key to known hosts
  ansible.posix.authorized_key:
    path: /etc/ssh/ssh_known_hosts
    key: "{{ git_forge_keys }}"  # ssh-keyscan
    user: "{{ tutor_user }}"
  when: git_forge_keys is defined
