---

- name: TUTOR | Pull all required images
  ansible.builtin.command: "{{ tutor_venv_path }}/{{ tutor_exec_name }} images pull {{ tutor_images | join(' ') }}"
  environment:
    TUTOR_ROOT: "{{ tutor_config_path }}"
    TUTOR_PLUGINS_ROOT: "{{ tutor_config_path }}/plugins"
    TUTOR_APP: "{{ tutor_app }}"
  become: true
  become_user: "{{ tutor_user }}"
  register: tutor_pull_result
  notify:
    - Reload tutor
  changed_when: '"Pull complete" in tutor_pull_result.stdout or "Downloaded newer image" in tutor_pull_result.stdout'
  tags:
    - tutor_update
    - tutor_deploy
