---
- name: Converge
  hosts: all
  become: true
  vars:
    tutor_service_enabled: false
    tutor_service_state: stopped
    tutor_init_arguments: "--non-interactive"
    tutor_force_reinstall: true
    tutor_user_local_management: false # Disable local management in tests

  tasks:
    - name: Load default variables
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/main.yml"

    - name: Include tutor role
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
