---
dependency:
  name: galaxy
  options:
    role-file: /dev/null

driver:
  name: docker

platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/run/docker.sock:/var/run/docker.sock
    cgroupns_mode: host
    privileged: true
    capabilities:
      - SYS_ADMIN
    security_opts:
      - apparmor:unconfined
    tmpfs:
      - /run
      - /tmp
    environment:
      container: docker

provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: yaml
      stdout_callback: yaml
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
  inventory:
    host_vars:
      instance:
        ansible_user: root
        docker_service_manage: false
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - verify
    - destroy