---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install required packages
      ansible.builtin.package:
        name:
          - python3-pip
          - python3-setuptools
          - git
          - curl
          - ca-certificates
          - gnupg
          - lsb-release
          - passwd
        state: present
