---
name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  DOCKER_BUILDX: "1"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Install geerlingguy.docker role
        run: ansible-galaxy install geerlingguy.docker

      - name: Install required collections
        run: ansible-galaxy collection install community.general ansible.posix

      - name: Run yamllint
        run: yamllint .

      - name: Run ansible-lint
        run: ansible-lint

  molecule:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install python requirements
        run: |
          pip install -r requirements.txt
          pip install molecule[docker]

      - name: Install geerlingguy.docker role
        run: ansible-galaxy install geerlingguy.docker

      - name: Install required collections
        run: ansible-galaxy collection install community.general ansible.posix

      - name: Create molecule docker scenario
        run: |
          mkdir -p molecule/docker
          cat > molecule/docker/molecule.yml << 'EOF'
          ---
          dependency:
            name: galaxy
          driver:
            name: docker
          platforms:
            - name: instance
              image: quay.io/ansible/ubuntu:22.04
              pre_build_image: true
          provisioner:
            name: ansible
            playbooks:
              converge: ../default/converge.yml
              verify: ../default/verify.yml
          verifier:
            name: ansible
          EOF

      - name: Run molecule test
        run: molecule test --scenario-name docker
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"