---
name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PY_COLORS: "1"
  ANSIBLE_FORCE_COLOR: "1"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
          # Устанавливаем зависимости напрямую
          ansible-galaxy role install geerlingguy.docker
          ansible-galaxy collection install community.general ansible.posix

      - name: Run linters
        run: |
          yamllint .
          ansible-lint

  test:
    name: Molecule Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
          # Устанавливаем зависимости напрямую
          ansible-galaxy role install geerlingguy.docker
          ansible-galaxy collection install community.general ansible.posix

      - name: Run Molecule tests
        run: molecule test
        env:
          MOLECULE_VERBOSITY: ${{ runner.debug == '1' && '1' || '0' }}