---
name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PY_COLORS: "1"
  ANSIBLE_FORCE_COLOR: "1"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Install geerlingguy.docker role
        run: ansible-galaxy install geerlingguy.docker

      - name: Install required collections
        run: ansible-galaxy collection install community.general ansible.posix

      - name: Run yamllint
        run: yamllint .

      - name: Run ansible-lint
        run: ansible-lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          ansible-galaxy install -r requirements.yml

      - name: Run Molecule tests
        run: molecule test
        env:
          MOLECULE_VERBOSITY: ${{ runner.debug == '1' && '1' || '0' }}
