---
name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  molecule-converge:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-molecule-${{ hashFiles('molecule/default/molecule.yml') }}
          restore-keys: |
            ${{ runner.os }}-molecule-

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Create a vm
        run: molecule create

      - name: Run test playbook
        run: molecule converge
